# Generated by Django 5.1 on 2024-11-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yaja', '0003_historicaldefaultmonday_historicaldefaultthursday_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultMonday',
        ),
        migrations.DeleteModel(
            name='DefaultThursday',
        ),
        migrations.DeleteModel(
            name='DefaultTuesday',
        ),
        migrations.DeleteModel(
            name='DefaultWednesday',
        ),
        migrations.RemoveField(
            model_name='historicaldefaultthursday',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldefaulttuesday',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldefaultwednesday',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalDefaultMonday',
        ),
        migrations.DeleteModel(
            name='HistoricalDefaultThursday',
        ),
        migrations.DeleteModel(
            name='HistoricalDefaultTuesday',
        ),
        migrations.DeleteModel(
            name='HistoricalDefaultWednesday',
        ),
    ]
